### ISSUE TITLE
Media Library Sidebar not showing on WP5.6 w/No Conflict Mode Enabled

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf#1175]
**Description**
Display issue in the Media Library when used in Gravity PDF context on WordPress 5.6 with Gravity Forms No Conflict Mode Enabled.

**Step To Reproduce**
1. Go to PDF Form Settings
2. Select Zadani Template
3. Select Template tab
4. Click the Upload button on the Background Image
5. Click existing media library

**Expected behavior**
Right sidebar should show content

**Screenshots**

**Additional context**
JavasScript console error

```
Uncaught TypeError: Cannot read property 'removeAllPlayers' of undefined
    at i.render (media-views.min.js?ver=5.6:2)
    at wp.Backbone.Subviews.<anonymous> (wp-backbone.min.js?ver=5.6:2)
    at underscore.min.js?ver=1.8.3:2
    at Function.v.each.v.forEach (underscore.min.js?ver=1.8.3:2)
    at wp.Backbone.Subviews._attach (wp-backbone.min.js?ver=5.6:2)
    at wp.Backbone.Subviews.set (wp-backbone.min.js?ver=5.6:2)
    at wp.Backbone.Subviews.add (wp-backbone.min.js?ver=5.6:2)
    at i.set (media-views.min.js?ver=5.6:2)
    at i.createSingle (media-views.min.js?ver=5.6:2)
    at p (backbone.min.js?ver=1.4.0:2)
```

**Comment by richardpbull** [comment]
Jake, how do you know this is anything to do with Gravity PDF? I don't have that installed and see the same error right now.

**Comment by jakejackson1** [comment]
Hey @richardpbull. It's not directly related to Gravity PDF and other plugins could have the same problem (but not something I've looked into much). In our case, when we load up the Rich Text Editor on the Gravity PDF settings pages when GF No Conflict mode is enabled, one of the newly-required JS files needed for the editor isn't being marked as _essential_ and GF is excluding it from loading (which is the purpose of No Conflict Mode). 

To fix, we'll locate the missing JS file and make sure it is doesn't get excluded on Gravity PDF pages when No Conflict Mode is enabled.

**Comment by richardpbull** [comment]
OK, I see! Thank you for your response, it helped me a lot. I've just turned off "no conflict mode" for GF and the error is resolved, and I can insert images again!
Thank you Jake, you saved me a big headache!

**Comment by ewb-git** [comment]
This is still causing an issue. Turning off "No conflict mode" fixes this as mentioned before.

If I go to form>notifications>add media, the "insert into post" option is greyed out, with "Uncaught TypeError: Cannot read property 'removeAllPlayers' of undefined" in console. Turning off "No conflict mode" allows me to add media to notifications. I would consider this bug, "NOT FIXED".
